version: 2.1

jobs:
  python_lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            pip install --user --progress-bar off flake8 typing
            flake8 .

  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            pip install --user --progress-bar off scipy pytest
            pip install --user --progress-bar off --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
            pip install --user --progress-bar off onnx onnxruntime
            pytest .

workflows:
  build:
    jobs:
      - python_lint
      - test
